import { CenterResult } from './types';

export const ELECTION_CENTERS_2026: CenterResult[] = [
  { id: 7, name: 'উল্টাখালী সরকারি প্রাথমিক বিদ্যালয়, উল্টাখালী', candidateVotes: 655, opponentVotes: 455, winner: 'লুৎফর রহমান' },
  { id: 8, name: 'ছনখোলা সরকারী প্রাথমিক বিদ্যালয়, ছনখোলা', candidateVotes: 1019, opponentVotes: 676, winner: 'লুৎফর রহমান' },
  { id: 9, name: 'ছনখোলা ঘোনার পাড়া ফরেস্ট বিট সরকারী প্রাথমিক বিদ্যালয়, ছনখোলা', candidateVotes: 1262, opponentVotes: 699, winner: 'লুৎফর রহমান' },
  { id: 10, name: 'তোতকখালী সরকারী প্রাথমিক বিদ্যালয়, তোতকখালী', candidateVotes: 1207, opponentVotes: 820, winner: 'লুৎফর রহমান' },
  { id: 11, name: 'পি, এম খালী আদর্শ আলিম মাদ্রাসা, জুমছড়ি', candidateVotes: 1069, opponentVotes: 884, winner: 'লুৎফর রহমান' },
  { id: 12, name: 'পরানিয়াপাড়া সরকারি প্রাথমিক বিদ্যালয়, পরানিয়া পাড়া', candidateVotes: 677, opponentVotes: 650, winner: 'লুৎফর রহমান' },
  { id: 16, name: 'মুহসিনিয়া সরকারি প্রাথমিক বিদ্যালয়, ধাউনখালী', candidateVotes: 852, opponentVotes: 643, winner: 'লুৎফর রহমান' },
  { id: 17, name: 'ধাউনখালী রহমানিয়া সরকারী প্রাথমিক বিদ্যালয়, ধাউনখালী', candidateVotes: 770, opponentVotes: 511, winner: 'লুৎফর রহমান' },
  { id: 18, name: 'মুহিচ্ছুন্নাহ তালীমুল কোরআন বালক | বালিকা মাদ্রাসা ও এতিমখানা, কাঠালিয়া মুড়া, পি.এম খালী', candidateVotes: 652, opponentVotes: 398, winner: 'লুৎফর রহমান' },
  { id: 19, name: 'পি, এম খালী সরকারী প্রাথমিক বিদ্যালয়, পিএমখালী', candidateVotes: 817, opponentVotes: 569, winner: 'লুৎফর রহমান' },
  { id: 30, name: 'খুরুস্কুল সরকোরি প্রাথমিক বিদ্যালয়, ডেইল পাড়া', candidateVotes: 762, opponentVotes: 608, winner: 'লুৎফর রহমান' },
  { id: 31, name: 'গণস্বাস্থ্য কেন্দ্র, খুরুস্কুল', candidateVotes: 1092, opponentVotes: 937, winner: 'লুৎফর রহমান' },
  { id: 33, name: 'মধ্য খুরুশকুল সরকারী প্রাথমিক বিদ্যালয়, হাট খোলা পাড়া', candidateVotes: 1482, opponentVotes: 915, winner: 'লুৎফর রহমান' },
  { id: 34, name: 'ড্যাফোডিল কিন্ডার গার্টেন, পাল পাড়া', candidateVotes: 1146, opponentVotes: 87, winner: 'লুৎফর রহমান' },
  { id: 35, name: 'খুরুশকুল শান্তি নিকেতন সরকারী প্রাথমিক বিদ্যালয়, হামজার ডেইল', candidateVotes: 1286, opponentVotes: 637, winner: 'লুৎফর রহমান' },
  { id: 36, name: 'গাজীর ডেইল দারুল উলুম দাখিল মাদ্রাসা, নুরানী একাডেমী ও এতিমখানা, গাজির ডেইল, খুরুস্কুল', candidateVotes: 1367, opponentVotes: 399, winner: 'লুৎফর রহমান' },
  { id: 37, name: 'খুরুস্কুল গার্লস হাইস্কুল, কোনারপাড়া', candidateVotes: 1130, opponentVotes: 681, winner: 'লুৎফর রহমান' },
  { id: 38, name: 'খুরুশকুল মনুপাড়া প্রাথমিক বিদ্যালয়, মনুপাড়া', candidateVotes: 665, opponentVotes: 534, winner: 'লুৎফর রহমান' },
  { id: 39, name: 'দক্ষিণ খুরুশকুল সরকারী প্রাথমিক বিদ্যালয়, দক্ষিণ পাড়া, (সাইক্লোন সেন্টার ভবন), দক্ষিণ পাড়া', candidateVotes: 1089, opponentVotes: 769, winner: 'লুৎফর রহমান' },
  { id: 40, name: 'দক্ষিণ খুরুশকুল সরকারী প্রাথমিক বিদ্যালয়, দক্ষিণপাড়া (পল্লী কবি জসিম উদ্দিন ভবন), দক্ষিণ পাড়া', candidateVotes: 914, opponentVotes: 620, winner: 'লুৎফর রহমান' },
  { id: 41, name: 'দক্ষিণ রাখাইন পাড়া সরকারী প্রাথমিক বিদ্যালয়, দক্ষিণ মগপাড়া', candidateVotes: 1420, opponentVotes: 792, winner: 'লুৎফর রহমান' },
  { id: 42, name: 'পশ্চিম চৌফলদন্ডী সরকারী প্রাথমিক বিদ্যালয়, পশ্চিম চৌফলদন্ডী', candidateVotes: 1034, opponentVotes: 690, winner: 'লুৎফর রহমান' },
  { id: 45, name: 'চৌফলদন্ডি আর্দশ উচ্চ বিদ্যালয়, চৌফলদন্ডি', candidateVotes: 569, opponentVotes: 556, winner: 'লুৎফর রহমান' },
  { id: 49, name: 'কুতুবদিয়া পাড়া মুহিসুন্নাহ দাখিল মাদ্রাসা, কুতুবদিয়া পাড়া', candidateVotes: 1358, opponentVotes: 1293, winner: 'লুৎফর রহমান' },
  { id: 50, name: 'উপকূলীয় আদর্শ শিক্ষা নিকেতন, সমিতি পাড়া', candidateVotes: 1229, opponentVotes: 883, winner: 'লুৎফর রহমান' },
  { id: 51, name: 'কুতুবদিয়া পাড়া উপকুলীয় নিন্ম মাধ্যমিক বিদ্যালয়, কুতুবদিয়া পাড়া', candidateVotes: 1225, opponentVotes: 701, winner: 'লুৎফর রহমান' },
  { id: 52, name: 'উত্তর নুনিয়ার ছড়া সরকারি প্রাথমিক বিদ্যালয়, উত্তর নুনিয়ারছড়া', candidateVotes: 1054, opponentVotes: 264, winner: 'লুৎফর রহমান' },
  { id: 53, name: 'শাহ সুফী হযরত আলী হোসেন ফকির (রহ:) সুন্নিয়া মাদ্রাসা, উত্তর নুনিয়ারছড়া', candidateVotes: 980, opponentVotes: 282, winner: 'লুৎফর রহমান' },
  { id: 54, name: 'বিমান বন্দর সরকারি প্রাথমিক বিদ্যালয়, মধ্যম নুনিয়ারছড়া', candidateVotes: 1042, opponentVotes: 279, winner: 'লুৎফর রহমান' },
  { id: 55, name: 'কক্সবাজার সরকারী মহিলা কলেজ, (প্রশাসনিক ভবন), বিমান বন্দর সড়ক', candidateVotes: 798, opponentVotes: 554, winner: 'লুৎফর রহমান' },
  { id: 56, name: 'কক্সবাজার সরকারী মহিলা কলেজ, (একাডেমিক ভবন), বিমান বন্দর সড়ক', candidateVotes: 653, opponentVotes: 442, winner: 'লুৎফর রহমান' },
  { id: 57, name: 'কস্তুরাঘাট সরকারি প্রাথমিক বিদ্যালয়, বদর মোকাম', candidateVotes: 467, opponentVotes: 390, winner: 'লুৎফর রহমান' },
  { id: 58, name: 'উমিদিয়া জামেয়া ইসলামীয়া, এন্ডারশন রোড', candidateVotes: 329, opponentVotes: 221, winner: 'লুৎফর রহমান' },
  { id: 59, name: 'পেশকার পাড়া সরকারি প্রাথমিক বিদ্যালয় কাম সাইক্লোন সেল্টার, পেশকার পাড়া', candidateVotes: 1255, opponentVotes: 915, winner: 'লুৎফর রহমান' },
  { id: 60, name: 'বার্মিজ সরকারি প্রাথমিক বিদ্যালয়, টেকপাড়া', candidateVotes: 760, opponentVotes: 681, winner: 'লুৎফর রহমান' },
  { id: 61, name: 'টেকপাড়া সরকারি প্রাথমিক বিদ্যালয়, টেকপাড়া', candidateVotes: 1105, opponentVotes: 938, winner: 'লুৎফর রহমান' },
  { id: 66, name: 'মধ্য ঝিলংজা সরকারি প্রাথমিক বিদ্যালয়, মধ্য ঝিলংজা', candidateVotes: 1112, opponentVotes: 963, winner: 'লুৎফর রহমান' },
  { id: 67, name: 'আবু বক্কর সিদ্দীক সরকারী প্রাথমিক বিদ্যালয়, এ, বি, সি ঘোনা', candidateVotes: 1257, opponentVotes: 1019, winner: 'লুৎফর রহমান' },
  { id: 69, name: 'রহমানিয়া মাদ্রাসা হেফজ খানা ও এতিমখানা, পাহাড়তলী', candidateVotes: 1396, opponentVotes: 1382, winner: 'লুৎফর রহমান' },
  { id: 70, name: 'ডি-ওয়ার্ড সরকারী প্রাথমিক বিদ্যালয়, দক্ষিণ টেকপাড়া', candidateVotes: 663, opponentVotes: 426, winner: 'লুৎফর রহমান' },
  { id: 71, name: 'বায়তুশ শরফ জববারিয়া একাডেমী (কারিগরী শিক্ষা ভবন), বইল্যা পাড়া', candidateVotes: 1054, opponentVotes: 559, winner: 'লুৎফর রহমান' },
  { id: 72, name: 'বায়তুশ শরফ জব্বারিয়া একাডেমী (বিজ্ঞান ও প্রযুক্তি ভবন), বইল্যা পাড়া', candidateVotes: 1248, opponentVotes: 151, winner: 'লুৎফর রহমান' },
  { id: 73, name: 'আল-আমিন একাডেমী, খাজা মঞ্জিল', candidateVotes: 1697, opponentVotes: 1077, winner: 'লুৎফর রহমান' },
  { id: 74, name: 'কক্সবাজার সরকারি উচ্চ বিদ্যালয়, গোলদিঘীর পশ্চিম পাড়', candidateVotes: 1396, opponentVotes: 692, winner: 'লুৎফর রহমান' },
  { id: 75, name: 'পৌর-প্রিপ্যারেটারী উচ্চ বিদ্যালয়, কাছারী পাহাড়', candidateVotes: 652, opponentVotes: 501, winner: 'লুৎফর রহমান' },
  { id: 76, name: 'পৌর-প্রিপ্যারেটারী প্রাথমিক বিদ্যালয় (মুল ভবন), কাছারী পাহাড়', candidateVotes: 476, opponentVotes: 315, winner: 'লুৎফর রহমান' },
  { id: 77, name: 'বাহার ছড়া সরকারি প্রাথমিক বিদ্যালয়, মধ্যম বাহার ছড়া', candidateVotes: 974, opponentVotes: 680, winner: 'লুৎফর রহমান' },
  { id: 78, name: 'সৈকত বালিকা উচ্চ বিদ্যালয়, ঝাউতলাগাড়ির মাঠ', candidateVotes: 906, opponentVotes: 482, winner: 'লুৎফর রহমান' },
  { id: 79, name: 'প্রাইমারী ট্রেনিং ইনস্টিটিউট, পশ্চিম বাহার ছড়া', candidateVotes: 1099, opponentVotes: 788, winner: 'লুৎফর রহমান' },
  { id: 80, name: 'লাইট হাউস দারুল উলুম মাদ্রাসা, লাইট হাউস পাড়া', candidateVotes: 1254, opponentVotes: 928, winner: 'লুৎফর রহমান' },
  { id: 81, name: 'কলাতলী আদর্শ উচ্চ বিদ্যালয়, কলাতলী', candidateVotes: 1049, opponentVotes: 598, winner: 'লুৎফর রহমান' },
  { id: 82, name: 'কলাতলী সরকারি প্রাথমিক বিদ্যালয়, কলাতলী', candidateVotes: 1556, opponentVotes: 1128, winner: 'লুৎফর রহমান' },
  { id: 85, name: 'নাপিতখালী মাধ্যমিক বিদ্যালয়, নাপিতখালী, ইসলামপুর, ঈদগাঁও, কক্সবাজার।', candidateVotes: 992, opponentVotes: 729, winner: 'লুৎফর রহমান' },
  { id: 88, name: 'উত্তর খান ঘোনা সরকারী প্রাথমিক বিদ্যালয়, উত্তর খান ঘোনা, ইসলামপুর, ঈদগাঁও, কক্সবাজার।', candidateVotes: 501, opponentVotes: 499, winner: 'লুৎফর রহমান' },
  { id: 91, name: 'ঈদগাঁও চরপাড়া ইয়াকুব আলী সরকারী প্রাথমিক বিদ্যালয়, উত্তর লরাবাগ, ইসলামাবাদ, ঈদগাঁও, কক্সবাজার।', candidateVotes: 920, opponentVotes: 771, winner: 'লুৎফর রহমান' },
  { id: 93, name: 'পূর্ব বোয়ালখালী শান্তিপুর বেসরকারী প্রাথমিক বিদ্যালয়, পূর্ব বোয়ালখালী ৫নং ওয়ার্ড ইসলামাবাদ, ঈদগাঁও, কক্সবাজার', candidateVotes: 664, opponentVotes: 656, winner: 'লুৎফর রহমান' },
  { id: 95, name: 'ঈদগাঁও জাহানারা ইসলাম বালিকা উচ্চ বিদ্যালয়, খোদাইবাড়ী, ইসলামাবাদ, ঈদগাঁও, কক্সবাজার।', candidateVotes: 1086, opponentVotes: 698, winner: 'লুৎফর রহমান' },
  { id: 96, name: 'খোদাই বাড়ী ওয়াহেদের পাড়া আছদআলী কোঃ সরকারী প্রাথমিক বিদ্যালয়, ওয়াহেদেরপাড়া, ইসলামাবাদ, ঈদগাঁও, কক্সবাজার', candidateVotes: 1276, opponentVotes: 1143, winner: 'লুৎফর রহমান' },
  { id: 97, name: 'গজালিয়া সরকারী প্রাথমিক বিদ্যালয়, মধ্যম গজালিয়া, ইসলামাবাদ, ঈদগাঁও, কক্সবাজার', candidateVotes: 788, opponentVotes: 773, winner: 'লুৎফর রহমান' },
  { id: 98, name: 'আলমাছিয়া ফাজিল মাদ্রাসা, জাগির পাড়া, ঈদগাও, কক্সবাজার।', candidateVotes: 843, opponentVotes: 833, winner: 'লুৎফর রহমান' },
  { id: 99, name: 'আজিজিয়া নুরুল উলুম মাদ্রাসা, মাইজপাড়া, ঈদগাঁও, কক্সবাজার', candidateVotes: 699, opponentVotes: 670, winner: 'লুৎফর রহমান' },
  { id: 100, name: 'দক্ষিণ মাইজপাড়া সরকারী প্রাথমিক বিদ্যালয়, দক্ষিণ মাইজ পাড়া, ঈদগাঁও, কক্সবাজার', candidateVotes: 834, opponentVotes: 813, winner: 'লুৎফর রহমান' },
  { id: 104, name: 'ভাদিতলা সরকারী প্রাথমিক বিদ্যালয়, ভাদিতলা, ঈদগাঁও, কক্সবাজার।', candidateVotes: 872, opponentVotes: 562, winner: 'লুৎফর রহমান' },
  { id: 105, name: 'আলী বিন আবি তালিব মাদ্রাসা, ভাদিতলা, ঈদগাঁও, কক্সবাজার |', candidateVotes: 1001, opponentVotes: 550, winner: 'লুৎফর রহমান' },
  { id: 106, name: 'পশ্চিম ভোমারিয়াঘোনা আল-কোরান নুরানী মাদ্রাসা, পশ্চিম ভোমরিয়াঘোনা, ঈদগাঁও, কক্সবাজার ।', candidateVotes: 1032, opponentVotes: 404, winner: 'লুৎফর রহমান' },
  { id: 107, name: 'ভোমারিয়াঘোনা সরকারী প্রাথমিক বিদ্যালয়, ভোমরিয়াঘোনা, ঈদগাঁও, কক্সবাজার ।', candidateVotes: 1035, opponentVotes: 703, winner: 'লুৎফর রহমান' },
  { id: 108, name: 'মাইজপাড়া সরকারী প্রাথমিক বিদ্যালয়, মাইজপাড়া, জালালাবাদ, ঈদগাঁও, কক্সবাজার।', candidateVotes: 1395, opponentVotes: 882, winner: 'লুৎফর রহমান' },
  { id: 109, name: 'দক্ষিণ লরাবাগ জমিরিয়া সরকারী প্রাথমিক বিদ্যালয়, দক্ষিণ লরাবাক, জালালাবাদ, ঈদগাঁও, কক্সবাজার।', candidateVotes: 1083, opponentVotes: 963, winner: 'লুৎফর রহমান' },
  { id: 110, name: 'ঈদগাঁও বাহারছড়া সরকারী প্রাথমিক বিদ্যালয়।, ফরাজী পাড়া, জালালাবাদ, ঈদগাঁও, কক্সবাজার।', candidateVotes: 940, opponentVotes: 760, winner: 'লুৎফর রহমান' },
  { id: 113, name: 'পূর্ব পোকখালী সরকারী প্রাথমিক বিদ্যালয়, পূর্ব পোকখালী, পোকখালী, ঈদগাঁও, কক্সবাজার ।', candidateVotes: 838, opponentVotes: 526, winner: 'লুৎফর রহমান' },
  { id: 114, name: 'মধ্যম পোকখালী সরকারী প্রাথমিক বিদ্যালয়, পোকখালী, ঈদগাঁও, কক্সবাজার |', candidateVotes: 904, opponentVotes: 723, winner: 'লুৎফর রহমান' },
  { id: 115, name: 'পশ্চিম পোকখালী সরকারী প্রাথমিক বিদ্যালয়, পশ্চিম পোকখালী, পোকখালী, ঈদগাঁও, কক্সবাজার |', candidateVotes: 1073, opponentVotes: 525, winner: 'লুৎফর রহমান' },
  { id: 116, name: 'নাইক্যংদিয়া সরকারী প্রাথমিক বিদ্যালয়, নাইক্যংদিয়া, পোকখালী, ঈদগাঁও, কক্সবাজার', candidateVotes: 1144, opponentVotes: 921, winner: 'লুৎফর রহমান' },
  { id: 117, name: 'পশ্চিম গোমাতলী সরকারী প্রাথমিক বিদ্যালয়, পশ্চিম গোমাতলী, পোকখালী, ঈদগাঁও, কক্সবাজার ।', candidateVotes: 1019, opponentVotes: 684, winner: 'লুৎফর রহমান' },
  { id: 118, name: 'পূর্ব গোমাতলী সরকারী প্রাথমিক বিদ্যালয়, পূর্ব পোকখালী, পোকখালী, ঈদগাঁও, কক্সবাজার', candidateVotes: 812, opponentVotes: 267, winner: 'লুৎফর রহমান' },
  { id: 120, name: 'ঈদগড় ইউনিয়ন পরিষদ কার্যালয়, গুইন্যাপাড়া', candidateVotes: 1133, opponentVotes: 955, winner: 'লুৎফর রহমান' },
  { id: 121, name: 'ঈদগড় বড়বিল সরকারী প্রাথমিক বিদ্যালয়, বড়বিল', candidateVotes: 1515, opponentVotes: 1221, winner: 'লুৎফর রহমান' },
  { id: 122, name: 'ছগিরাকাটা মাদানিয়া তাহসীনুল কুরআন মাদ্রাসা, ছগিরা কাটা', candidateVotes: 1392, opponentVotes: 1114, winner: 'লুৎফর রহমান' },
  { id: 123, name: 'উত্তর বড় বিল সরকারী প্রাথমিক বিদ্যালয়, বড়বিল', candidateVotes: 1038, opponentVotes: 573, winner: 'লুৎফর রহমান' },
  { id: 125, name: 'থোয়াংগের কাটা সরকারী প্রাথমিক বিদ্যালয়, থোয়াঙ্গা কাটা', candidateVotes: 623, opponentVotes: 564, winner: 'লুৎফর রহমান' },
  { id: 127, name: 'ক্যাজরবিল সরকারি প্রাথমিক বিদ্যালয়, ক্যাজর বিল', candidateVotes: 389, opponentVotes: 351, winner: 'লুৎফর রহমান' },
  { id: 132, name: 'গর্জনিয়া সরকারি প্রাথমিক বিদ্যালয়, কচ্ছপিয়া, পশ্চিম তিতার পাড়া', candidateVotes: 1174, opponentVotes: 1054, winner: 'লুৎফর রহমান' },
  { id: 134, name: 'মৌলভীরকাটা সরকারী প্রাথমিক বিদ্যালয়, মৌলভী কাটা', candidateVotes: 1881, opponentVotes: 1382, winner: 'লুৎফর রহমান' },
  { id: 135, name: 'মনিরঝিল সরকারী প্রাথমিক বিদ্যালয় মনিরঝিল', candidateVotes: 1352, opponentVotes: 1260, winner: 'লুৎফর রহমান' },
  { id: 136, name: 'কাউয়ারখোপ সরকারী প্রাথমিক বিদ্যালয়, পশ্চিম পাড়া', candidateVotes: 1092, opponentVotes: 1069, winner: 'লুৎফর রহমান' },
  { id: 138, name: 'লট উখিয়ারঘোনা সরকারী প্রাথমিক বিদ্যালয়, লট উখিয়ারঘোনা।', candidateVotes: 913, opponentVotes: 694, winner: 'লুৎফর রহমান' },
  { id: 139, name: 'উখিয়ারঘোনা সরকারী প্রাথমিক বিদ্যালয়, টিলা পাড়া।', candidateVotes: 1232, opponentVotes: 525, winner: 'লুৎফর রহমান' },
  { id: 140, name: 'দারুল উলুম মাইনুল ইসলাম মাদ্রাসা হেফজখানা ও এতিমখানা (লামার পাড়া মাদ্রাসা), লামার পাড়া', candidateVotes: 1062, opponentVotes: 510, winner: 'লুৎফর রহমান' },
  { id: 141, name: 'আলহাজ্ব ফজল আম্বিয়া উচ্চ বিদ্যালয় অফিসের চর, (চরপাড়া)', candidateVotes: 965, opponentVotes: 734, winner: 'লুৎফর রহমান' },
  { id: 142, name: 'রামু কেন্দ্রীয় সরকারী প্রাথমিক বিদ্যালয়, অফিসের চর', candidateVotes: 999, opponentVotes: 661, winner: 'লুৎফর রহমান' },
  { id: 143, name: 'লম্বরী পাড়া সরকারী প্রাথমিক বিদ্যালয়, লম্বরী পাড়া', candidateVotes: 951, opponentVotes: 852, winner: 'লুৎফর রহমান' },
  { id: 145, name: 'রামু খিজারি বার্মিজ সরকারী প্রাথমিক বিদ্যালয়, দক্ষিণ উত্তর শ্রীকুল', candidateVotes: 756, opponentVotes: 296, winner: 'লুৎফর রহমান' },
  { id: 146, name: 'পূর্ব মেরংলোয়া ইসলামিয়া রহমানিয়া মাদ্রাসা, পূর্ব মেরংলোয়া', candidateVotes: 1111, opponentVotes: 743, winner: 'লুৎফর রহমান' },
  { id: 147, name: 'রামু খিজারী সরকারী আদর্শ উচ্চ বিদ্যালয়, বড়ুয়া পাড়া', candidateVotes: 871, opponentVotes: 394, winner: 'লুৎফর রহমান' },
  { id: 149, name: 'উত্তর ফতেখাঁরকুল সরকারী প্রাথমিক বিদ্যালয়, চ্যালনা বণিক', candidateVotes: 1156, opponentVotes: 800, winner: 'লুৎফর রহমান' },
  { id: 150, name: 'নন্দাখালী সরকারী প্রাথমিক বিদ্যালয়, বড় পাড়া', candidateVotes: 854, opponentVotes: 617, winner: 'লুৎফর রহমান' },
  { id: 151, name: 'পশ্চিম জোয়ারিয়ানালা সরকারী প্রাথমিক বিদ্যালয়, ইলিশিয়া পাড়া', candidateVotes: 1465, opponentVotes: 678, winner: 'লুৎফর রহমান' },
  { id: 152, name: 'পূর্ব জোয়ারিয়ানালা সরকারি প্রাথমিক বিদ্যালয়, পূর্ব জোয়ারিয়ানালা', candidateVotes: 645, opponentVotes: 499, winner: 'লুৎফর রহমান' },
  { id: 153, name: 'ঘোনার পাড়া সরকারী প্রাথমিক বিদ্যালয়, ঘোনার পাড়া', candidateVotes: 1450, opponentVotes: 726, winner: 'লুৎফর রহমান' },
  { id: 154, name: 'নোনাছড়ি সরকারী প্রাথমিক বিদ্যালয়, পশ্চিম নোনাছড়ি', candidateVotes: 1104, opponentVotes: 576, winner: 'লুৎফর রহমান' },
  { id: 155, name: 'উত্তর মিঠাছড়ি সরকারী প্রাথমিক বিদ্যালয়, চৌধুরী পাড়া', candidateVotes: 1262, opponentVotes: 989, winner: 'লুৎফর রহমান' },
  { id: 156, name: 'জোয়ারিয়ানালা এইচ. এম. সাঁচি উচ্চ বিদ্যালয়, সওদাগর পাড়া', candidateVotes: 1628, opponentVotes: 1008, winner: 'লুৎফর রহমান' },
  { id: 157, name: 'রাজারকুল সরকারী প্রাথমিক বিদ্যালয়, হালদারকুল', candidateVotes: 1335, opponentVotes: 1287, winner: 'লুৎফর রহমান' },
  { id: 158, name: 'রাজারকুল আজিজুল উলুম মাদ্রসা, এতিমখানা ভবন, পশ্চিম নয়া পাড়া', candidateVotes: 1285, opponentVotes: 660, winner: 'লুৎফর রহমান' },
  { id: 159, name: 'রাজারকুল আজিজুর উলুম মাদ্রসা, শিক্ষা ভবন, পশ্চিম নয়া পাড়া', candidateVotes: 1172, opponentVotes: 444, winner: 'লুৎফর রহমান' },
  { id: 160, name: 'রাম কোট সরকারী প্রাথমিক বিদ্যালয়, দক্ষিন ঘোনার পাড়া', candidateVotes: 1218, opponentVotes: 548, winner: 'লুৎফর রহমান' },
  { id: 161, name: 'পূর্ব রাজারকুল সরকারী প্রাথমিক বিদ্যালয়, বড়ুয়া পাড়া', candidateVotes: 1335, opponentVotes: 793, winner: 'লুৎফর রহমান' },
  { id: 165, name: 'উমখালী সরকারী প্রাথমিক বিদ্যালয়, আবু বকর বাপের পাড়া', candidateVotes: 1995, opponentVotes: 1054, winner: 'লুৎফর রহমান' },
  { id: 166, name: 'পানের ছড়া সরকারী প্রাথমিক বিদ্যালয়, পূর্ব পানের ছড়া', candidateVotes: 1632, opponentVotes: 743, winner: 'লুৎফর রহমান' },
  { id: 167, name: 'দারিয়ার দিঘী সরকারী প্রাথমিক বিদ্যালয়, বড় ডেবা', candidateVotes: 704, opponentVotes: 653, winner: 'লুৎফর রহমান' },
  { id: 168, name: 'মাদরাসা আব্দুল্লাহ বিন আব্বাস (রাঃ) আল ইসলামিয়া, পশ্চিম থোয়াংগাকাটা', candidateVotes: 1017, opponentVotes: 686, winner: 'লুৎফর রহমান' },
  { id: 169, name: 'কালার পাড়া সরকারী প্রাথমিক বিদ্যালয়, কালার পাড়া', candidateVotes: 1302, opponentVotes: 623, winner: 'লুৎফর রহমান' },
  { id: 170, name: 'খুনিয়া পালং সরকারী প্রাথমিক বিদ্যালয়, উত্তর খুনিয়াপালং', candidateVotes: 1438, opponentVotes: 785, winner: 'লুৎফর রহমান' },
  { id: 171, name: 'গোয়ালিয়া পালং সরকারী প্রাথমিক বিদ্যালয়, পশ্চিম গোয়ালিয়াপালং', candidateVotes: 1545, opponentVotes: 1104, winner: 'লুৎফর রহমান' },
  { id: 172, name: 'পেঁচারদ্বীপ সরকারী প্রাথমিক বিদ্যালয়, পেঁচার দ্বীপ', candidateVotes: 1144, opponentVotes: 789, winner: 'লুৎফর রহমান' },
  { id: 173, name: 'ধেছুয়া পালং উচ্চ বিদ্যালয়, পূর্ব ধেচুয়াপালং', candidateVotes: 1412, opponentVotes: 918, winner: 'লুৎফর রহমান' },
  { id: 174, name: 'ধেচুয়া পালং সরকারী প্রাথমিক বিদ্যালয়, মধ্যম ধেচুয়াপালং', candidateVotes: 1091, opponentVotes: 777, winner: 'লুৎফর রহমান' },
  { id: 175, name: 'ধোয়া পালং সরকারী প্রাথমিক বিদ্যালয়, ধোয়া পালং', candidateVotes: 1342, opponentVotes: 919, winner: 'লুৎফর রহমান' },
  { id: 178, name: 'আল-জামিয়া-আল-ইসলামিয়া দারুল উলুম চাকমারকুল, রামু, পশ্চিম চাকমারকুল', candidateVotes: 1475, opponentVotes: 1310, winner: 'লুৎফর রহমান' },
  { id: 179, name: 'ইসলামিয়া আলিয়া আশরাফুল উলুম মাদ্রাসা, সিকদার পাড়া', candidateVotes: 751, opponentVotes: 736, winner: 'লুৎফর রহমান' },
  { id: 180, name: 'নাদেরুজ্জামান উচ্চ বিদ্যালয়, কাদমার পাড়া (৫ নং ওয়ার্ড)', candidateVotes: 955, opponentVotes: 928, winner: 'লুৎফর রহমান' },
  { id: 181, name: 'ধলিরছড়া সরকারি প্রাথমিক বিদ্যালয়, পানির ছড়া মোরা পাড়া', candidateVotes: 1494, opponentVotes: 1319, winner: 'লুৎফর রহমান' },
  { id: 1, name: 'ভারুয়াখালী সরকারী প্রাথমিক বিদ্যালয়, সাবেক পাড়া', candidateVotes: 475, opponentVotes: 680, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 2, name: 'ভারুয়াখালী পশ্চিম পাড়া সরকারি প্রাথমিক বিদ্যালয়, ভারুয়াখালী', candidateVotes: 824, opponentVotes: 1352, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 3, name: 'ভারুয়াখালী দারুল উলুম আলিম মাদ্রাসা, বানিয়াছড়া', candidateVotes: 710, opponentVotes: 965, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 4, name: 'ভারুয়াখালী আদর্শ উচ্চ বিদ্যালয়, হাজী পাড়া', candidateVotes: 895, opponentVotes: 1061, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 5, name: 'চৌধুরী পাড়া ও ঘোনারপাড়া সরকারী প্রাথমিক বিদ্যালয়, ঘোনারপাড়া', candidateVotes: 624, opponentVotes: 629, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 6, name: 'আবু সামা সওদাগর পাড়া সরকারি প্রাথমিক বিদ্যালয়, বড় চৌধুরী পাড়া', candidateVotes: 892, opponentVotes: 1105, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 13, name: 'পশ্চিম ডিকপাড়া সরকারী প্রাথমিক বিদ্যালয়, ডিকপাড়া', candidateVotes: 389, opponentVotes: 613, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 14, name: 'বাংলাবাজার কে, জি স্কুল, নয়া পাড়া', candidateVotes: 856, opponentVotes: 1249, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 15, name: 'ডিকপাড়া সরকারী প্রাথমিক বিদ্যালয়, ডিকপাড়া', candidateVotes: 765, opponentVotes: 995, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 20, name: 'লারপাড়া সরকারী প্রাথমিক বিদ্যালয়, লার পাড়া', candidateVotes: 964, opponentVotes: 1181, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 21, name: 'হাজী পাড়া সরকারী প্রাথমিক বিদ্যালয়, হাজী পাড়া', candidateVotes: 1482, opponentVotes: 1861, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 22, name: 'মোঃ ইলিয়াছ মিয়া চৌধুরী উচ্চ বিদ্যালয়, জানার ঘোনা', candidateVotes: 688, opponentVotes: 1987, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 23, name: 'মুহুরী পাড়া সরকারী প্রাথমিক বিদ্যালয়, মুহুরী পাড়া', candidateVotes: 1024, opponentVotes: 2069, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 24, name: 'মুক্তারকুল সরকারি প্রাথমিক বিদ্যালয়, মুক্তারকুল', candidateVotes: 827, opponentVotes: 1597, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 25, name: 'ছুরতিয়া ফাজিল ডিগ্রী মাদ্রাসা, মুক্তারকুল', candidateVotes: 428, opponentVotes: 869, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 26, name: 'দক্ষিণ খরুলিয়া সরকারী প্রাথমিক বিদ্যালয়, দক্ষিণ খরুলিয়া', candidateVotes: 1016, opponentVotes: 1487, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 27, name: 'পূর্ব খরুলিয়া সরকারী প্রাথমিক বিদ্যালয়, পূর্ব খরুলিয়া', candidateVotes: 862, opponentVotes: 1186, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 28, name: 'তেতৈয়া সরকারী প্রাথমিক বিদ্যালয়, তেতৈয়া', candidateVotes: 867, opponentVotes: 1327, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 29, name: 'তেতৈয়া তাফহিমুল কোরআন আলীম মাদ্রাসা, ডেইল পাড়া', candidateVotes: 552, opponentVotes: 900, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 32, name: 'খুরুশকুল উচ্চ বিদ্যালয়, ফকির পাড়া', candidateVotes: 1144, opponentVotes: 1245, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 43, name: 'পশ্চিম চৌফলদণ্ডী হাকিমিয়া সরকারি প্রাথমিক বিদ্যালয়, কোনারপাড়া', candidateVotes: 784, opponentVotes: 926, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 44, name: '৪৪ নং আলিয়াপাড়া সরকারি প্রাথমিক বিদ্যালয় ও বহুমুখী দুর্যোগ আশ্রয়কেন্দ্র, চৌফলদন্ডী', candidateVotes: 1112, opponentVotes: 1125, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 46, name: 'কালু ফকির পাড়া বালিকা দাখিল মাদ্রাসা, কালু ফকির পাড়া', candidateVotes: 536, opponentVotes: 794, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 47, name: 'নতুন মহাল সরকারি প্রাথমিক বিদ্যালয়, নতুন মহাল', candidateVotes: 611, opponentVotes: 758, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 48, name: 'পুকুরিয়া ঘোনা সরকারী প্রাথমিক বিদ্যালয়, পুকুরিয়া ঘোনা', candidateVotes: 439, opponentVotes: 918, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 62, name: 'শহীদ তিতুমীর ইনস্টিটিউট, তারাবনিয়ারছড়া', candidateVotes: 671, opponentVotes: 759, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 63, name: 'সাহিত্যিকা উচ্চ বিদ্যালয়, সাহিত্যিকা পল্লী', candidateVotes: 1023, opponentVotes: 1472, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 64, name: 'কক্সবাজার হাশেমিয়া কামিল মাস্টার্স মাদ্রাসা (একাডেমীক ভবন দক্ষিনাংশ), দক্ষিণ রুমালিয়ার ছড়া', candidateVotes: 671, opponentVotes: 1152, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 65, name: 'কক্সবাজার হাশেমিয়া কামিল মাস্টার্স মাদ্রাসা (একাডেমীক ভবন পূর্বাংশ), দক্ষিণ রুমালিয়ার ছড়া', candidateVotes: 656, opponentVotes: 1075, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 68, name: 'কক্সবাজার টেকনিক্যাল স্কুল এন্ড কলেজ, দক্ষিণ রুমালিয়ার ছড়া', candidateVotes: 736, opponentVotes: 762, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 83, name: 'তালিমুল কোরআন হেফজ ও এতিমখানা, মাদ্রাসা, বাঁশকাটা, ইসলামপুর, ঈদগাঁও, কক্সবাজার।', candidateVotes: 937, opponentVotes: 1009, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 84, name: 'মধ্যম নাপিতখালী সরকারী প্রাথমিক বিদ্যালয়, মধ্যম নাপিত খালী, ইসলামপুর, ঈদগাঁও, কক্সবাজার', candidateVotes: 949, opponentVotes: 1283, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 86, name: 'পূর্ব নাপিত খালী সরকারী প্রাথমিক বিদ্যালয়, পূর্ব বামনকাটা, ইসলামপুর, ঈদগাঁও, কক্সবাজার।', candidateVotes: 986, opponentVotes: 1062, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 87, name: 'ইসলামপুর ইসলামিয়া দাখিল মাদ্রাসা, ধর্মের ছড়া, ইসলামপুর, ঈদগাঁও, কক্সবাজার।', candidateVotes: 813, opponentVotes: 1197, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 89, name: 'ঈদগাঁও টেকপাড়া সরকারী প্রাথমিক বিদ্যালয়, টেকপাড়া, ইসলামাবাদ, ঈদগাঁও, কক্সবাজার।', candidateVotes: 526, opponentVotes: 580, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 90, name: 'পাহাশিয়াখালী সরকারী প্রাথমিক বিদ্যালয়, পাহাশিয়াখালী, ইসলামাবাদ, ঈদগাঁও, কক্সবাজার।', candidateVotes: 483, opponentVotes: 990, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 92, name: 'ইছাখালী সরকারী প্রাথমিক বিদ্যালয়, দক্ষিণ সাতজোলাকাটা', candidateVotes: 516, opponentVotes: 877, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 94, name: 'ইউছুপেরখীল সরকারী প্রাথমিক বিদ্যালয়, ইউছুপেরখিল, ইসলামাবাদ, ঈদগাঁও, কক্সবাজার।', candidateVotes: 760, opponentVotes: 865, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 101, name: 'ঈদগাঁও শাহ জববারিয়া আদর্শ দাখিল মাদ্রাসা, মেহেরঘোনা, ঈদগাঁও, কক্সবাজার।', candidateVotes: 1003, opponentVotes: 1354, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 102, name: 'কালির ছড়া সরকারী প্রাথমিক বিদ্যালয়, কালিরছড়া, ঈদগাঁও, কক্সবাজার।', candidateVotes: 682, opponentVotes: 764, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 103, name: 'মাছুয়াখালী সরকারী প্রাথমিক বিদ্যালয়, মাছুয়াখালী, ঈদগাঁও, কক্সবাজার।', candidateVotes: 498, opponentVotes: 619, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 111, name: 'পালাকাটা গুলজার বেগম দাখিল মাদ্রাসা, পালাকাটা, জালালাবাদ, ঈদগাঁও, কক্সবাজার।', candidateVotes: 802, opponentVotes: 1504, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 112, name: 'পোকখালী আদর্শ উচ্চ বিদ্যালয়, পশ্চিম ইছাখালী, পোকখালী, ।ঈদগাঁও, কক্সবাজার।', candidateVotes: 646, opponentVotes: 656, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 119, name: 'ঈদগড় বদরমোকাম জামেয়া ফেরদৌসীয়া দাখিল মাদ্রাসা, বদরমোকাম', candidateVotes: 551, opponentVotes: 749, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 124, name: 'পূর্ব জুমছড়ি সরকারি প্রাথমিক বিদ্যালয়, পূর্ব জুমছড়ি', candidateVotes: 886, opponentVotes: 1150, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 126, name: 'মাঝির কাটা সরকারী প্রাথমিক বিদ্যালয়, মাঝির কাটা', candidateVotes: 937, opponentVotes: 1129, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 128, name: 'জাউচ পাড়া সরকারি প্রাথমিক বিদ্যালয়, জাউচ পাড়া', candidateVotes: 812, opponentVotes: 1007, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 129, name: 'গর্জনিয়া উচ্চ বিদ্যালয় বোমাংখিল।, বোমাংখিল।', candidateVotes: 649, opponentVotes: 719, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 130, name: 'কচ্ছপিয়া সরকারী প্রাথমিক বিদ্যালয় দক্ষিণ পাড়া', candidateVotes: 1290, opponentVotes: 1844, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 131, name: 'গর্জনিয়া ফয়জুল উলুম ফাজিল মাদ্রাসা, নতুন মিয়াজির পাড়া', candidateVotes: 1191, opponentVotes: 1456, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 133, name: 'শুকমনিয়া সরকারি প্রাথমিক বিদ্যালয়, শুকমনিয়া', candidateVotes: 1553, opponentVotes: 1630, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 137, name: 'কাউয়ারখোপ হাকিম রকিমা উচ্চ বিদ্যালয়, মধ্যম পাড়া', candidateVotes: 503, opponentVotes: 671, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 144, name: 'মন্ডল পাড়া সরকারী প্রাথমিক বিদ্যালয়, মন্ডল পাড়া', candidateVotes: 423, opponentVotes: 779, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 148, name: 'পশ্চিম মেরুংলোয়া সরকারী প্রাথমিক বিদ্যালয়, পশ্চিম মেরুংলোয়া', candidateVotes: 863, opponentVotes: 961, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 162, name: 'দক্ষিণ মিঠাছড়ি উচ্চ বিদ্যালয়, দক্ষিণ মিঠাছড়ি', candidateVotes: 1096, opponentVotes: 1377, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 163, name: 'নিজের পাড়া সরকারি প্রাথমিক বিদ্যালয়, নিজের পাড়া', candidateVotes: 1151, opponentVotes: 1501, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 164, name: 'চেইন্দা সরকারী প্রাথমিক বিদ্যালয়, চেইন্দা', candidateVotes: 1314, opponentVotes: 2073, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 176, name: 'দক্ষিণ চাকমারকুল সরকারী প্রাথমিক বিদ্যালয়, মাতবর পাড়া।', candidateVotes: 1159, opponentVotes: 1281, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 177, name: 'জারাইলতলী উচ্চ বিদ্যালয়, জারাইলতলা', candidateVotes: 1511, opponentVotes: 1521, winner: 'নিকটতম প্রতিদ্বন্ধি' },
  { id: 182, name: 'রশিদনগর ইউনিয়ন পরিষদ কার্যালয়, হরিতলা', candidateVotes: 1108, opponentVotes: 1274, winner: 'নিকটতম প্রতিদ্বন্ধি' },
];
